#!/bin/bash

./onecourse.py https://app.testudo.umd.edu/soc/202008/AASP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AAST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AGNR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AMSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AMST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ANSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ANTH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AOSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARAB > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARCH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/AREC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARHU > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARMY > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARTH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ARTT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ASTR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BCHM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BEES > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BIOE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BIOL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BIOM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BIPH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BISI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BMGT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BSCI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BSCV > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BSGC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BSOS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BSST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUAC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUDT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUFN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BULM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUMK > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUSI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUSM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/BUSO > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CBMG > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CCJS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CHBE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CHEM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CHIN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CHPH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CLAS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CLFS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CMLT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CMSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/COMM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPBE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPET > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPGH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPJT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPMS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPPL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSD > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSF > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSG > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/CPSS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/DANC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EALL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ECON > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDCP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDHD > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDHI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDMS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDSP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EDUC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENAE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENCE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENCH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENCO > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENEE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENES > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENFP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENGL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENMA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENME > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENPM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENRE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENSE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENSP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENTM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ENTS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/EPIB > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/FGSM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/FILM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/FIRE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/FMSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/FREN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GEMS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GEOG > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GEOL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GERM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GREK > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/GVPT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HACS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HDCC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HEBR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HEIP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HESI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HESP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HHUM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HISP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HIST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HLMN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HLSA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HLSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HLTH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/HONR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/IDEA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/IMMR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/INAG > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/INFM > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/INST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ISRL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/ITAL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/JAPN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/JOUR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/JWST > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/KNES > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/KORA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LARC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LASC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LATN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LBSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LGBT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/LING > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MATH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MEES > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MIEH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MITH > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MLAW > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MLSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MOCB > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MUED > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MUSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/MUSP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/NACS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/NAVY > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/NEUR > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/NFSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/NIAS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PEER > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PERS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PHIL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PHPE > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PHSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PHYS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PLCY > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PLSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PORT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/PSYC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/RDEV > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/RELS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/RUSS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SLAA > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SLLC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SOCY > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SPAN > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SPHL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/STAT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/SURV > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/TDPS > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/THET > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/TLPL > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/TLTC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/UMEI > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/UNIV > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/URSP > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/USLT > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/VMSC > /dev/null &
./onecourse.py https://app.testudo.umd.edu/soc/202008/WMST > /dev/null &